# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


## This file defines parameters for a prediction experiment.

###############################################################################
#                                IMPORTANT!!!
# This params file is dynamically generated by the RunExperimentPermutations
# script. Any changes made manually will be over-written the next time
# RunExperimentPermutations is run!!!
###############################################################################


from nupic.frameworks.opf.expdescriptionhelpers import importBaseDescription

# the sub-experiment configuration
config ={
  'aggregationInfo' : {'seconds': 0, 'fields': [], 'months': 0, 'days': 0, 'years': 0, 'hours': 0, 'microseconds': 0, 'weeks': 0, 'minutes': 0, 'milliseconds': 0},
  'modelParams' : {'sensorParams': {'encoders': {u'rwidth': {'name': 'rwidth', 'clipInput': True, 'n': 117, 'fieldname': 'rwidth', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, '_classifierInput': {'classifierOnly': True, 'clipInput': True, 'n': 64, 'fieldname': 'rpos', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, u'lpos': {'name': 'lpos', 'clipInput': True, 'n': 517, 'fieldname': 'lpos', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, u'lwidth': {'name': 'lwidth', 'clipInput': True, 'n': 112, 'fieldname': 'lwidth', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, u'rpos': None}}, 'inferenceType': 'NontemporalMultiStep', 'spParams': {'synPermInactiveDec': 0.09516831738960979}, 'tpParams': {'minThreshold': 9, 'activationThreshold': 13, 'pamLength': 1}, 'clParams': {'alpha': 0.01183971581823866}},

}

mod = importBaseDescription('../description.py', config)
locals().update(mod.__dict__)
